-- MySQL Script generated by MySQL Workbench
-- 03/17/16 11:06:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hateagram
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hateagram
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hateagram` DEFAULT CHARACTER SET utf8 ;
USE `hateagram` ;

-- -----------------------------------------------------
-- Table `hateagram`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hateagram`.`users` (
  `userName` VARCHAR(255) NOT NULL,
  `realName` VARCHAR(255) NULL DEFAULT NULL,
  `age` INT(11) NULL DEFAULT NULL,
  `pass` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`userName`),
  UNIQUE INDEX `userName` (`userName` ASC),
  UNIQUE INDEX `email` (`email` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hateagram`.`posttypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hateagram`.`posttypes` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `postType` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID` (`ID` ASC),
  UNIQUE INDEX `postType` (`postType` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hateagram`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hateagram`.`posts` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `postType` INT(11) NOT NULL,
  `User_ID` VARCHAR(255) NOT NULL,
  `postDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `filename` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID` (`ID` ASC),
  INDEX `User_ID` (`User_ID` ASC),
  INDEX `postType` (`postType` ASC),
  CONSTRAINT `posts_ibfk_1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `hateagram`.`users` (`userName`),
  CONSTRAINT `posts_ibfk_2`
    FOREIGN KEY (`postType`)
    REFERENCES `hateagram`.`posttypes` (`ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hateagram`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hateagram`.`comments` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `CommentText` VARCHAR(255) NOT NULL,
  `Post_ID` INT(11) NOT NULL,
  `User_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID` (`ID` ASC),
  INDEX `Post_ID` (`Post_ID` ASC),
  INDEX `User_ID` (`User_ID` ASC),
  CONSTRAINT `comments_ibfk_1`
    FOREIGN KEY (`Post_ID`)
    REFERENCES `hateagram`.`posts` (`ID`),
  CONSTRAINT `comments_ibfk_2`
    FOREIGN KEY (`User_ID`)
    REFERENCES `hateagram`.`users` (`userName`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hateagram`.`dislikes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hateagram`.`dislikes` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Post_ID` INT(11) NOT NULL,
  `User_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID` (`ID` ASC),
  UNIQUE INDEX `unique_like` (`Post_ID` ASC, `User_ID` ASC),
  INDEX `User_ID` (`User_ID` ASC),
  CONSTRAINT `dislikes_ibfk_1`
    FOREIGN KEY (`Post_ID`)
    REFERENCES `hateagram`.`posts` (`ID`),
  CONSTRAINT `dislikes_ibfk_2`
    FOREIGN KEY (`User_ID`)
    REFERENCES `hateagram`.`users` (`userName`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hateagram`.`followers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hateagram`.`followers` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `User_ID` VARCHAR(255) NULL DEFAULT NULL,
  `Follower_ID` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID` (`ID` ASC),
  UNIQUE INDEX `unique_following` (`User_ID` ASC, `Follower_ID` ASC),
  INDEX `Follower_ID` (`Follower_ID` ASC),
  CONSTRAINT `followers_ibfk_1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `hateagram`.`users` (`userName`),
  CONSTRAINT `followers_ibfk_2`
    FOREIGN KEY (`Follower_ID`)
    REFERENCES `hateagram`.`users` (`userName`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hateagram`.`following`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hateagram`.`following` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `User_ID` VARCHAR(255) NOT NULL,
  `Following_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID` (`ID` ASC),
  UNIQUE INDEX `unique_following` (`User_ID` ASC, `Following_ID` ASC),
  INDEX `Following_ID` (`Following_ID` ASC),
  CONSTRAINT `following_ibfk_1`
    FOREIGN KEY (`User_ID`)
    REFERENCES `hateagram`.`users` (`userName`),
  CONSTRAINT `following_ibfk_2`
    FOREIGN KEY (`Following_ID`)
    REFERENCES `hateagram`.`users` (`userName`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hateagram`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hateagram`.`likes` (
  `ID` INT(11) NOT NULL AUTO_INCREMENT,
  `Post_ID` INT(11) NOT NULL,
  `User_ID` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID` (`ID` ASC),
  UNIQUE INDEX `unique_like` (`Post_ID` ASC, `User_ID` ASC),
  INDEX `User_ID` (`User_ID` ASC),
  CONSTRAINT `likes_ibfk_1`
    FOREIGN KEY (`Post_ID`)
    REFERENCES `hateagram`.`posts` (`ID`),
  CONSTRAINT `likes_ibfk_2`
    FOREIGN KEY (`User_ID`)
    REFERENCES `hateagram`.`users` (`userName`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
